# Generated by Django 6.0.3 on 2026-08-14 19:01

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCVSettings',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_enabled', models.BooleanField(default=False)),
                ('show_contact', models.BooleanField(default=False)),
                ('show_attributes', models.BooleanField(default=True)),
                ('show_career', models.BooleanField(default=True)),
                ('show_achievements', models.BooleanField(default=True)),
                ('show_highlights', models.BooleanField(default=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'player_cv_settings',
            },
        ),
    ]
