# Generated by Django 6.0.3 on 2026-03-29 10:53

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('sports', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'hashtags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True)),
                ('post_type', models.CharField(choices=[('normal', 'Normal')], default='normal', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers', 'Followers')], default='public', max_length=20)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('comments_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='organization.organization')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='sports.sport')),
            ],
            options={
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='posts.post')),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='posts.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='PostHashtag',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='posts.hashtag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_hashtags', to='posts.post')),
            ],
            options={
                'db_table': 'post_hashtags',
            },
        ),
        migrations.CreateModel(
            name='PostMedia',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.post')),
            ],
            options={
                'db_table': 'post_media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PostMention',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('mentioned_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
                ('mentioned_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentions', to='posts.post')),
            ],
            options={
                'db_table': 'post_mentions',
            },
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_posts',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_created_2e2442_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author_user'], name='posts_author__146b16_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['author_org'], name='posts_author__ef9350_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['sport'], name='posts_sport_i_346799_idx'),
        ),
        migrations.AddConstraint(
            model_name='post',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('author_org__isnull', True), ('author_user__isnull', False)), models.Q(('author_org__isnull', False), ('author_user__isnull', True)), _connector='OR'), name='post_author_user_or_org'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['post'], name='likes_post_id_cf2001_idx'),
        ),
        migrations.AddIndex(
            model_name='like',
            index=models.Index(fields=['user'], name='likes_user_id_4c8dad_idx'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_like'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comments_post_id_7ee550_idx'),
        ),
        migrations.AddConstraint(
            model_name='posthashtag',
            constraint=models.UniqueConstraint(fields=('post', 'hashtag'), name='unique_post_hashtag'),
        ),
        migrations.AddIndex(
            model_name='postmedia',
            index=models.Index(fields=['post'], name='post_media_post_id_9187e2_idx'),
        ),
        migrations.AddConstraint(
            model_name='postmention',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mentioned_org__isnull', True), ('mentioned_user__isnull', False)), models.Q(('mentioned_org__isnull', False), ('mentioned_user__isnull', True)), _connector='OR'), name='mention_user_or_org'),
        ),
        migrations.AddConstraint(
            model_name='savedpost',
            constraint=models.UniqueConstraint(fields=('user', 'post'), name='unique_saved_post'),
        ),
    ]
