# Generated by Django 6.0.3 on 2026-04-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_like_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes_breakdown',
            field=models.JSONField(default=dict),
        ),
    ]
