# Generated by Django 6.0.3 on 2026-04-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_likes_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
