# Generated by Django 6.0.3 on 2026-07-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_city_post_country_code_post_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='postmedia',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
