# Generated by Django 6.0.3 on 2026-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_remove_savedpost_unique_saved_post_savedpost_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
