# Generated by Django 6.0.3 on 2026-03-28 18:08

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('team', 'Team'), ('academy', 'Academy')], max_length=20)),
                ('level', models.CharField(blank=True, choices=[('amateur', 'Amateur'), ('professional', 'Professional'), ('youth', 'Youth')], max_length=20)),
                ('logo', models.URLField(blank=True)),
                ('cover_image', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_organizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('coach', 'Coach'), ('staff', 'staff')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_members',
            },
        ),
        migrations.CreateModel(
            name='OrganizationSport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to='organization.organization')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizations', to='sports.sport')),
            ],
            options={
                'db_table': 'organization_sports',
            },
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_by'], name='organizatio_created_7b4623_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['organization', 'user'], name='organizatio_organiz_324912_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_org_user'),
        ),
        migrations.AddIndex(
            model_name='organizationsport',
            index=models.Index(fields=['organization', 'sport'], name='organizatio_organiz_c545fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationsport',
            constraint=models.UniqueConstraint(fields=('organization', 'sport'), name='unique_org_sport'),
        ),
    ]
