# Generated by Django 6.0.3 on 2026-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organizationprofile_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
