# Generated by Django 6.0.3 on 2026-07-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organizationprofile_following_count'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='organizationprofile',
            index=models.Index(fields=['followers_count'], name='organizatio_followe_3e8bda_idx'),
        ),
    ]
