# Generated by Django 6.0.3 on 2026-08-20 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_organizationprofile_is_public_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='username',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only lowercase letters, numbers and underscore allowed', regex='^[a-z0-9_]+$')]),
        ),
    ]
