# Generated by Django 6.0.3 on 2026-08-26 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organization_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
