# Generated by Django 6.0.3 on 2026-10-05 18:17
# Organization.timezone — the org's calendar, and the seed for every
# recruitment it posts. Pairs with recruitments/0021, which adds the same
# column to Recruitment; they are two migrations only because Django cannot
# put fields from two apps in one.
#
# NO DATA MIGRATION AND NO BACKFILL. The default is
# settings.RECRUITMENT_TIMEZONE, so every existing row keeps behaving exactly
# as it did under the old global setting.


import utils.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationlocation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='timezone',
            field=models.CharField(default=utils.timezones.default_timezone, max_length=64, validators=[utils.timezones.validate_timezone]),
        ),
    ]
