# Generated by Django 6.0.3 on 2026-03-28 19:29

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
                ('following_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='organization.organization')),
                ('following_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'follows',
                'indexes': [models.Index(fields=['follower'], name='follows_followe_ca9b09_idx'), models.Index(fields=['following_user'], name='follows_followi_e6a6bc_idx'), models.Index(fields=['following_org'], name='follows_followi_b79864_idx'), models.Index(fields=['-created_at'], name='follows_created_a41b9a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('following_org__isnull', True), ('following_user__isnull', False)), models.Q(('following_org__isnull', False), ('following_user__isnull', True)), _connector='OR'), name='follow_user_or_org_only'), models.UniqueConstraint(fields=('follower', 'following_user'), name='unique_user_follow'), models.UniqueConstraint(fields=('follower', 'following_org'), name='unique_org_follow')],
            },
        ),
    ]
