# Generated by Django 6.0.3 on 2026-08-02 13:11

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0007_organizationprofile_organizatio_followe_3e8bda_idx'),
        ('recruitments', '0006_recruitmentapplication_shared_name_and_more'),
        ('sports', '0004_alter_sport_icon_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=100)),
                ('entry_type', models.CharField(choices=[('club_team', 'Club Team'), ('national_team', 'National Team'), ('loan', 'Loan'), ('academy', 'Academy'), ('school_college', 'School / College'), ('other', 'Other')], default='club_team', max_length=20)),
                ('squad_level', models.CharField(blank=True, choices=[('youth', 'Youth'), ('reserve', 'Reserve'), ('senior', 'Senior')], max_length=20)),
                ('age_group', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('verification_status', models.CharField(choices=[('self_reported', 'Self Reported'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='self_reported', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('recruitment', 'Recruitment')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_entries', to='organization.organization')),
                ('positions', models.ManyToManyField(blank=True, related_name='career_entries', to='sports.sportposition')),
                ('recruitment_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_entries', to='recruitments.recruitmentapplication')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='career_entries', to='sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_entries', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_career_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'career_entries',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_current'], name='career_entr_user_id_c95dbe_idx'), models.Index(fields=['user', 'start_date'], name='career_entr_user_id_ab9f35_idx'), models.Index(fields=['organization', 'verification_status'], name='career_entr_organiz_b6aa47_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='career_entry_valid_date_range'), models.CheckConstraint(condition=models.Q(('is_current', False), ('end_date__isnull', True), _connector='OR'), name='career_entry_current_has_no_end_date'), models.UniqueConstraint(condition=models.Q(('recruitment_application__isnull', False)), fields=('recruitment_application',), name='unique_career_entry_per_application')],
            },
        ),
    ]
