# Generated by Django 6.0.3 on 2026-07-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highlight',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='highlight',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
