# Generated by Django 6.0.3 on 2026-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_connections_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
