# Generated by Django 6.0.3 on 2026-04-04 08:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_cover_photo_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='height_cm',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(300)]),
        ),
    ]
