# Generated by Django 6.0.3 on 2026-04-15 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='direct_pair_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
