# Generated by Django 6.0.3 on 2026-07-17 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_conversation_direct_pair_key'),
        ('organization', '0007_organizationprofile_organizatio_followe_3e8bda_idx'),
        ('posts', '0009_postmedia_height_postmedia_width'),
        ('recruitments', '0006_recruitmentapplication_shared_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='media_duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='message',
            name='media_size_bytes',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='media_thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='message',
            name='media_width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='posts.post'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recruitments.recruitment'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('system', 'System'), ('shared_post', 'Shared Post'), ('shared_recruitment', 'Shared Recruitment')], default='text', max_length=20),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'message_type'], name='messaging_m_convers_d70066_idx'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shared_post__isnull', True), ('shared_recruitment__isnull', True)), models.Q(('message_type', 'shared_post'), ('shared_post__isnull', False), ('shared_recruitment__isnull', True)), models.Q(('message_type', 'shared_recruitment'), ('shared_post__isnull', True), ('shared_recruitment__isnull', False)), _connector='OR'), name='message_shared_object_matches_type'),
        ),
    ]
