# Generated by Django 6.0.3 on 2026-03-27 19:27

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sports', '0002_remove_sport_sports_name_847b57_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon_name', models.CharField(blank=True, max_length=100)),
                ('icon_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'sports',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='sports_name_847b57_idx')],
            },
        ),
        migrations.CreateModel(
            name='SportAttribute',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(choices=[('select', 'Select'), ('multi_select', 'Multi Select'), ('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean')], max_length=20)),
                ('is_required', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='sports.sport')),
            ],
            options={
                'db_table': 'sport_attributes',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='SportAttributeOption',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=100)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='sports.sportattribute')),
            ],
            options={
                'db_table': 'sport_attribute_options',
            },
        ),
        migrations.CreateModel(
            name='SportPosition',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='sports.sport')),
            ],
            options={
                'db_table': 'sport_positions',
            },
        ),
        migrations.CreateModel(
            name='UserAttributeValue',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('value_text', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportattribute')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sports.sportattributeoption')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_attribute_values',
            },
        ),
        migrations.CreateModel(
            name='UserSport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('experience_level', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('professional', 'Professional')], max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_sports',
            },
        ),
        migrations.CreateModel(
            name='UserSportPosition',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sportposition')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_positions',
            },
        ),
        migrations.AddIndex(
            model_name='sportattribute',
            index=models.Index(fields=['sport', 'display_order'], name='sport_attri_sport_i_9177bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='sportattribute',
            constraint=models.UniqueConstraint(fields=('sport', 'name'), name='unique_sport_attribute'),
        ),
        migrations.AddConstraint(
            model_name='sportattributeoption',
            constraint=models.UniqueConstraint(fields=('attribute', 'value'), name='unique_attribute_option'),
        ),
        migrations.AddConstraint(
            model_name='sportposition',
            constraint=models.UniqueConstraint(fields=('sport', 'name'), name='unique_position_per_sport'),
        ),
        migrations.AddIndex(
            model_name='userattributevalue',
            index=models.Index(fields=['user', 'sport'], name='user_attrib_user_id_d5a71e_idx'),
        ),
        migrations.AddConstraint(
            model_name='userattributevalue',
            constraint=models.CheckConstraint(condition=models.Q(('option__isnull', False), ('value_text__isnull', False), _connector='OR'), name='attribute_value_required'),
        ),
        migrations.AddIndex(
            model_name='usersport',
            index=models.Index(fields=['user', 'sport'], name='user_sports_user_id_fd68db_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersport',
            constraint=models.UniqueConstraint(fields=('user', 'sport'), name='unique_user_sport'),
        ),
        migrations.AddConstraint(
            model_name='usersport',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user',), name='unique_primary_sport_per_user'),
        ),
        migrations.AddIndex(
            model_name='usersportposition',
            index=models.Index(fields=['user', 'sport'], name='user_positi_user_id_723628_idx'),
        ),
        migrations.AddConstraint(
            model_name='usersportposition',
            constraint=models.UniqueConstraint(fields=('user', 'position'), name='unique_user_position'),
        ),
        migrations.AddConstraint(
            model_name='usersportposition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('user', 'sport'), name='unique_primary_position_per_sport'),
        ),
    ]
