# Generated by Django 6.0.3 on 2026-04-18 09:18

import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationLocation',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(db_index=True, max_length=5)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'organization_locations',
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('logo', models.URLField(blank=True)),
                ('logo_public_id', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.URLField(blank=True)),
                ('cover_image_public_id', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('level', models.CharField(blank=True, choices=[('amateur', 'Amateur'), ('professional', 'Professional'), ('youth', 'Youth')], max_length=20)),
                ('followers_count', models.PositiveIntegerField(default=0)),
                ('posts_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organization_profiles',
            },
        ),
        migrations.RemoveIndex(
            model_name='organization',
            name='organizatio_slug_5b8b37_idx',
        ),
        migrations.AddField(
            model_name='organization',
            name='username',
            field=models.CharField(db_index=True, default=1, max_length=50, unique=True, validators=[django.core.validators.RegexValidator(message='Only lowercase letters, numbers, underscore and dot allowed', regex='^[a-z0-9_.]+$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('club', 'Club'), ('team', 'Team'), ('academy', 'Academy'), ('school', 'School / College')], max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('coach', 'Coach'), ('staff', 'staff')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['username'], name='organizatio_usernam_c035f7_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['type'], name='organizatio_type_c31c58_idx'),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['created_at'], name='organizatio_created_8a4b5e_idx'),
        ),
        migrations.AddField(
            model_name='organizationlocation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organization.organization'),
        ),
        migrations.RemoveField(
            model_name='organization',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='description',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='level',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='website',
        ),
        migrations.AddIndex(
            model_name='organizationlocation',
            index=models.Index(fields=['organization'], name='organizatio_organiz_42afd0_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationlocation',
            index=models.Index(fields=['city'], name='organizatio_city_1cc7a3_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationlocation',
            index=models.Index(fields=['country_code'], name='organizatio_country_5a6974_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationlocation',
            index=models.Index(fields=['latitude', 'longitude'], name='organizatio_latitud_001a4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationlocation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('organization',), name='unique_primary_location_per_org'),
        ),
    ]
