# Generated by Django 6.0.3 on 2026-04-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organizationlocation_organizationprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
