# Generated by Django 6.0.3 on 2026-04-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='cover_image',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='logo',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='website',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
