# Generated by Django 6.0.3 on 2026-08-30 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_organization_is_suspended'),
        ('shared', '0002_remove_location_unique_external_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationlocation',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_locations', to='shared.location'),
        ),
    ]
