# Generated by Django 6.0.3 on 2026-08-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='image',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
