# Generated by Django 6.0.3 on 2026-08-03 10:56

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('organization', '0007_organizationprofile_organizatio_followe_3e8bda_idx'),
        ('sports', '0004_alter_sport_icon_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('achievement_type', models.CharField(choices=[('team_trophy', 'Team Trophy'), ('individual_award', 'Individual Award'), ('record', 'Record'), ('milestone', 'Milestone'), ('certification', 'Certification'), ('other', 'Other')], default='individual_award', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('event_name', models.CharField(blank=True, max_length=150)),
                ('level', models.CharField(blank=True, choices=[('school', 'School'), ('district', 'District'), ('state', 'State'), ('national', 'National'), ('international', 'International'), ('club_local', 'Club / Local')], max_length=20)),
                ('awarded_by_name', models.CharField(blank=True, max_length=150)),
                ('achieved_date', models.DateField()),
                ('image', models.URLField(blank=True)),
                ('image_public_id', models.CharField(blank=True, max_length=255)),
                ('reference_link', models.URLField(blank=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('verification_status', models.CharField(choices=[('self_reported', 'Self Reported'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='self_reported', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('awarded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_achievements', to='organization.organization')),
                ('career_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achievements', to='careers.careerentry')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='achievements', to='sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'achievements',
                'ordering': ['-is_pinned', '-achieved_date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_pinned'], name='achievement_user_id_81874c_idx'), models.Index(fields=['user', 'achieved_date'], name='achievement_user_id_88b9e1_idx'), models.Index(fields=['awarded_by', 'verification_status'], name='achievement_awarded_d4438a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('awarded_by__isnull', False), ('verification_status', 'self_reported'), _connector='OR'), name='achievement_verification_requires_issuer')],
            },
        ),
    ]
