# Generated by Django 6.0.3 on 2026-08-31 12:19

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('document', models.CharField(max_length=20)),
                ('version', models.CharField(max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'legal_acceptances',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', 'document', '-accepted_at'], name='legal_user_doc_recent_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'document', 'version'), name='unique_acceptance_per_version')],
            },
        ),
    ]
