# Generated by Django 6.0.3 on 2026-04-03 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='icon_name',
            field=models.CharField(blank=True, help_text='iconify library icon name', max_length=100),
        ),
    ]
