# Generated by Django 6.0.3 on 2026-09-10 04:51

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('linked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardians',
            },
        ),
        migrations.CreateModel(
            name='GuardianConsentEvent',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('requested', 'Requested'), ('resent', 'Resent'), ('approved', 'Approved'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], max_length=20)),
                ('method', models.CharField(blank=True, choices=[('goatza_account', 'Existing Goatza account'), ('separate_contact', 'Separate contact'), ('shared_contact', 'Shared contact')], max_length=20)),
                ('level', models.CharField(choices=[('acknowledged', 'Acknowledged'), ('verified', 'Verified')], default='acknowledged', max_length=20)),
                ('notice_version', models.CharField(max_length=20)),
                ('parent_name_given', models.CharField(blank=True, max_length=150)),
                ('parent_birthdate_given', models.DateField(blank=True, null=True)),
                ('token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('token_expires_at', models.DateTimeField(null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_consent_events', to=settings.AUTH_USER_MODEL)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='guardians.guardian')),
            ],
            options={
                'db_table': 'guardian_consent_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['email'], name='guardians_email_69eb1d_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['phone'], name='guardians_phone_b8e364_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('email', ''), _negated=True), models.Q(('phone', ''), _negated=True), _connector='OR'), name='guardian_email_or_phone_required'),
        ),
        migrations.AddIndex(
            model_name='guardianconsentevent',
            index=models.Index(fields=['child', '-created_at'], name='guardian_child_recent_idx'),
        ),
    ]
