# Generated by Django 6.0.3 on 2026-08-18 17:08

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSignup',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('district', models.CharField(blank=True, choices=[('thiruvananthapuram', 'Thiruvananthapuram'), ('kollam', 'Kollam'), ('pathanamthitta', 'Pathanamthitta'), ('alappuzha', 'Alappuzha'), ('kottayam', 'Kottayam'), ('idukki', 'Idukki'), ('ernakulam', 'Ernakulam'), ('thrissur', 'Thrissur'), ('palakkad', 'Palakkad'), ('malappuram', 'Malappuram'), ('kozhikode', 'Kozhikode'), ('wayanad', 'Wayanad'), ('kannur', 'Kannur'), ('kasaragod', 'Kasaragod'), ('other', 'Other')], max_length=50)),
                ('state', models.CharField(blank=True, default='Kerala', max_length=50)),
                ('sport', models.CharField(default='football', max_length=30)),
                ('position', models.CharField(blank=True, choices=[('goalkeeper', 'Goalkeeper'), ('defender', 'Defender'), ('midfielder', 'Midfielder'), ('left_wing', 'Left Wing'), ('right_wing', 'Right Wing'), ('striker', 'Striker')], max_length=40)),
                ('level', models.CharField(blank=True, choices=[('school', 'School'), ('club', 'Club'), ('district', 'District'), ('state', 'State'), ('university', 'University'), ('none', 'None / just play')], max_length=30)),
                ('club_or_academy', models.CharField(blank=True, max_length=150)),
                ('signup_number', models.PositiveIntegerField(unique=True)),
                ('ref_code', models.CharField(max_length=12, unique=True)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'waitlist_player_signups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['district'], name='waitlist_pl_distric_863a3c_idx'), models.Index(fields=['position'], name='waitlist_pl_positio_c63c7b_idx'), models.Index(fields=['created_at'], name='waitlist_pl_created_1005b5_idx')],
            },
        ),
    ]
