# Generated by Django 6.0.3 on 2026-04-08 09:23

import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('city', 'City'), ('place', 'Place')], max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('external_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='shared_loca_name_e8b18c_idx'), models.Index(fields=['type'], name='shared_loca_type_e9d349_idx'), models.Index(fields=['latitude', 'longitude'], name='shared_loca_latitud_88f808_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('external_id',), name='unique_external_location'), models.UniqueConstraint(fields=('latitude', 'longitude', 'name'), name='unique_location_combination')],
            },
        ),
    ]
