# Generated by Django 6.0.3 on 2026-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_external_location',
        ),
        migrations.RemoveConstraint(
            model_name='location',
            name='unique_location_combination',
        ),
        migrations.AddField(
            model_name='location',
            name='coords_fetched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='provider',
            field=models.CharField(choices=[('google', 'Google'), ('manual', 'Manual')], default='google', max_length=20),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['coords_fetched_at'], name='shared_loca_coords__d13910_idx'),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('provider', 'external_id'), name='unique_provider_external_location'),
        ),
    ]
