# Generated by Django 6.0.3 on 2026-08-26 09:55

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_shared_profile_messages'),
        ('moderation', '0001_initial'),
        ('organization', '0009_alter_organization_username'),
        ('posts', '0012_postmedia_size_bytes'),
        ('recruitments', '0008_recruitmentdiscoverimpression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('spam', 'Spam'), ('harassment', 'Harassment'), ('hate_speech', 'Hate Speech'), ('nudity_sexual', 'Nudity / Sexual Content'), ('violence', 'Violence'), ('scam_fraud', 'Scam / Fraud'), ('impersonation_fake', 'Impersonation / Fake Account'), ('minor_safety', 'Minor Safety'), ('self_harm', 'Self Harm'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('content_snapshot', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Reviewing'), ('action_taken', 'Action Taken'), ('dismissed', 'Dismissed')], db_index=True, default='pending', max_length=20)),
                ('is_priority', models.BooleanField(db_index=True, default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('action_taken', models.CharField(choices=[('none', 'None'), ('content_removed', 'Content Removed'), ('warning_sent', 'Warning Sent'), ('account_suspended', 'Account Suspended')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reported_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='posts.comment')),
                ('reported_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='messaging.message')),
                ('reported_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='organization.organization')),
                ('reported_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='posts.post')),
                ('reported_recruitment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to='recruitments.recruitment')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to='organization.organization')),
                ('reporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'reports',
                'indexes': [models.Index(fields=['status', '-created_at'], name='reports_status_d7deb7_idx'), models.Index(fields=['reported_user'], name='reports_reporte_225900_idx'), models.Index(fields=['reported_org'], name='reports_reporte_7169ee_idx'), models.Index(fields=['reported_post'], name='reports_reporte_e9666b_idx'), models.Index(fields=['reported_comment'], name='reports_reporte_00aa51_idx'), models.Index(fields=['reported_message'], name='reports_reporte_c4fae7_idx'), models.Index(fields=['reported_recruitment'], name='reports_reporte_d3ac39_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('reporter_org__isnull', True), ('reporter_user__isnull', False)), models.Q(('reporter_org__isnull', False), ('reporter_user__isnull', True)), _connector='OR'), name='reporter_user_or_org'), models.CheckConstraint(condition=models.Q(models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', False)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', False), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', False), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', False), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', False), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', False), ('reported_user__isnull', True)), _connector='OR'), name='report_exactly_one_target'), models.UniqueConstraint(condition=models.Q(('reported_user__isnull', False), ('reporter_user__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_user', 'reported_user'), name='uniq_open_report_user_user'), models.UniqueConstraint(condition=models.Q(('reported_org__isnull', False), ('reporter_user__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_user', 'reported_org'), name='uniq_open_report_user_org'), models.UniqueConstraint(condition=models.Q(('reported_post__isnull', False), ('reporter_user__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_user', 'reported_post'), name='uniq_open_report_user_post'), models.UniqueConstraint(condition=models.Q(('reported_comment__isnull', False), ('reporter_user__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_user', 'reported_comment'), name='uniq_open_report_user_comment'), models.UniqueConstraint(condition=models.Q(('reported_message__isnull', False), ('reporter_user__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_user', 'reported_message'), name='uniq_open_report_user_message'), models.UniqueConstraint(condition=models.Q(('reported_recruitment__isnull', False), ('reporter_user__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_user', 'reported_recruitment'), name='uniq_open_report_user_recruitment'), models.UniqueConstraint(condition=models.Q(('reported_user__isnull', False), ('reporter_org__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_org', 'reported_user'), name='uniq_open_report_org_user'), models.UniqueConstraint(condition=models.Q(('reported_org__isnull', False), ('reporter_org__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_org', 'reported_org'), name='uniq_open_report_org_org'), models.UniqueConstraint(condition=models.Q(('reported_post__isnull', False), ('reporter_org__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_org', 'reported_post'), name='uniq_open_report_org_post'), models.UniqueConstraint(condition=models.Q(('reported_comment__isnull', False), ('reporter_org__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_org', 'reported_comment'), name='uniq_open_report_org_comment'), models.UniqueConstraint(condition=models.Q(('reported_message__isnull', False), ('reporter_org__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_org', 'reported_message'), name='uniq_open_report_org_message'), models.UniqueConstraint(condition=models.Q(('reported_recruitment__isnull', False), ('reporter_org__isnull', False), ('status__in', ['pending', 'reviewing'])), fields=('reporter_org', 'reported_recruitment'), name='uniq_open_report_org_recruitment')],
            },
        ),
    ]
