# Generated by Django 6.0.3 on 2026-08-26 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0004_shared_profile_messages'),
        ('moderation', '0002_report'),
        ('organization', '0009_alter_organization_username'),
        ('posts', '0012_postmedia_size_bytes'),
        ('recruitments', '0008_recruitmentdiscoverimpression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='report',
            name='report_exactly_one_target',
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', False)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', False), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', False), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', False), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', False), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', False), ('reported_user__isnull', True)), models.Q(('reported_comment__isnull', True), ('reported_message__isnull', True), ('reported_org__isnull', True), ('reported_post__isnull', True), ('reported_recruitment__isnull', True), ('reported_user__isnull', True)), _connector='OR'), name='report_at_most_one_target'),
        ),
    ]
