# Generated by Django 6.0.3 on 2026-03-29 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='follow_user_or_org_only',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_user_follow',
        ),
        migrations.RemoveConstraint(
            model_name='follow',
            name='unique_org_follow',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='follows_followe_ca9b09_idx',
        ),
        migrations.RemoveIndex(
            model_name='follow',
            name='follows_created_a41b9a_idx',
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='follow',
            name='follower_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower_user'], name='follows_followe_5054d7_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower_org'], name='follows_followe_f609d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('follower_org__isnull', True), ('follower_user__isnull', False)), models.Q(('follower_org__isnull', False), ('follower_user__isnull', True)), _connector='OR'), name='follower_user_or_org'),
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('following_org__isnull', True), ('following_user__isnull', False)), models.Q(('following_org__isnull', False), ('following_user__isnull', True)), _connector='OR'), name='following_user_or_org'),
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
    ]
