# Generated by Django 6.0.3 on 2026-05-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_city_userprofile_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='connections_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='following_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
