# Generated by Django 6.0.3 on 2026-07-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_accounts_us_role_1fa9a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_role_confirmed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('coach', 'Coach'), ('scout', 'Scout'), ('org_user', 'Org User')], default='player', max_length=20),
        ),
    ]
