# Generated by Django 6.0.3 on 2026-09-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_privacy_accepted_at_user_privacy_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
