# Generated by Django 6.0.3 on 2026-09-08 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    """
    The two age-gate columns on User. NO BACKFILL, deliberately.

    Every existing row keeps country_code="" and the profile birthdate it
    already had, which is usually NULL. That is not an oversight: there is no
    honest value to write. Guessing a jurisdiction from the profile's location
    would be exactly the conflation the field comment on the model warns
    against, and inventing a birthdate would be inventing personal data. The
    "unknown" state is handled — accounts/constants.is_minor reads a missing
    birthdate as a minor, which is the safe answer — so leaving these blank is
    a correct state to leave the table in rather than a gap to be papered over.

    UserProfile.birthdate is untouched and stays nullable. The requirement is
    enforced at signup, not by the column; making it NOT NULL would demand
    exactly the invented data described above for every row already there.
    """

    dependencies = [
        ('accounts', '0012_user_deletion_requested_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthdate_corrections',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
