# Generated by Django 6.0.3 on 2026-09-10 04:51

import logging

from django.db import migrations, models

logger = logging.getLogger(__name__)

# Rows per UPDATE. The pending set is a small minority of any realistic table —
# minors with a known birthdate — but it is written as a handful of batched
# updates rather than one statement with an unbounded IN list.
BATCH_SIZE = 500


def backfill_guardian_consent_status(apps, schema_editor):
    """
    Give every existing account the status it would have had if the guardian
    system had always been there.

    THE CHECK IS REDONE INLINE, and it has to be. ``User.is_minor`` is a
    property on the real model, and ``apps.get_model`` hands back the
    HISTORICAL one, which has fields and nothing else — calling it here would
    raise. So the two halves are put together by hand exactly as the property
    does it: the birthdate from the profile row, the legal country from the
    user, both through ``accounts.constants.is_minor``.

    Importing that module inside the function (rather than at the top, or
    copying its tables into this file) is deliberate. It holds no model state —
    it is a country-to-age lookup and two date functions — so there is no
    historical version of it to be wrong about, and freezing a copy here would
    mean this backfill and the running signup gate disagreeing about who is a
    minor the moment a country's rule is researched and added.

    THE THREE OUTCOMES:

      * Not a minor -> ``not_needed``. Nobody's parent has to be asked.

      * A minor WITH a birthdate -> ``pending``. This is the real work of the
        migration: these accounts exist, they are children, and no guardian has
        ever been asked about them. Pending is the honest description of that
        and the state the consent service will pick up from.

      * A minor ONLY because the birthdate is missing -> ``not_needed``, and
        counted. ``constants.is_minor(None, ...)`` answers True on purpose —
        for a GATE, unknown age must read as a child. For this column it would
        be wrong: it would drop every account created before the signup
        birthdate requirement (see 0013 — the column stays nullable precisely
        because those rows exist) into a consent queue that would then chase a
        guardian for adults who never had a birthdate on file. Those rows are
        not "children", they are UNASSESSED, and the count is logged so that
        the size of that population is a known number before anything starts
        gating on this column rather than a surprise discovered later.
    """
    from accounts import constants as account_constants

    User = apps.get_model("accounts", "User")
    UserProfile = apps.get_model("accounts", "UserProfile")

    # One dict instead of a join, because the join is the wrong shape: a User
    # may have NO profile row at all (a Google account created before signup
    # wrote both, a staff-made user, a fixture — the same case is_minor guards
    # against), and those users must still be classified rather than dropped.
    birthdate_by_user = dict(
        UserProfile.objects.values_list("user_id", "birthdate")
    )

    pending_ids = []
    unknown_birthdate = 0

    for user_id, country_code in User.objects.values_list("id", "country_code").iterator():
        birthdate = birthdate_by_user.get(user_id)

        if birthdate is None:
            unknown_birthdate += 1
            continue

        if account_constants.is_minor(birthdate, country_code):
            pending_ids.append(user_id)

    for start in range(0, len(pending_ids), BATCH_SIZE):
        (
            User.objects
            .filter(id__in=pending_ids[start:start + BATCH_SIZE])
            .update(guardian_consent_status="pending")
        )

    # Everything else keeps the column default written by AddField above, so
    # only the pending set is touched.
    logger.info(
        "guardian_consent_status backfill: %s minor(s) set pending, "
        "%s row(s) left not_needed because no birthdate is on file.",
        len(pending_ids),
        unknown_birthdate,
    )


def reverse_noop(apps, schema_editor):
    # Nothing to undo: dropping the column removes the state entirely.
    pass


class Migration(migrations.Migration):
    """
    The denormalized guardian-consent column on User, plus its backfill.

    Both in one migration, following 0009: the column and the values it is
    supposed to hold arrive together, so there is no window in which the field
    exists and every row claims not_needed.
    """

    dependencies = [
        ('accounts', '0013_user_birthdate_corrections_user_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='guardian_consent_status',
            field=models.CharField(choices=[('not_needed', 'Not needed'), ('pending', 'Pending'), ('approved', 'Approved'), ('withdrawn', 'Withdrawn')], default='not_needed', max_length=20),
        ),
        migrations.RunPython(backfill_guardian_consent_status, reverse_noop),
    ]
