"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os 
import sys
from pathlib import Path
from datetime import timedelta

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv
load_dotenv()


def env_list(name, default=""):
    """Read a comma-separated env var into a list of trimmed, non-empty items.

    Hosts and origins differ per environment, so they live in the environment
    rather than in this file. An unset or blank var falls back to `default`.
    """
    raw = os.getenv(name) or default
    return [item.strip() for item in raw.split(",") if item.strip()]

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# Fail at import rather than boot with a signing key of None. A server that
# starts without a real SECRET_KEY signs sessions and password-reset tokens
# with an empty value — worse than one that refuses to start.
if not SECRET_KEY:
    raise ImproperlyConfigured(
        "DJANGO_SECRET_KEY is not set. Set it to a long random string in the "
        "environment (or .env for local development)."
    )


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

# The single switch every environment-dependent setting below is derived from.
IS_PROD = not DEBUG

if IS_PROD:
    ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured(
            "DJANGO_ALLOWED_HOSTS must be set in production as a "
            "comma-separated list of hostnames this app answers on, e.g. "
            "DJANGO_ALLOWED_HOSTS=goatza-backend.onrender.com,api.goatza.com"
        )
else:
    ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1")


# ------ SECURITY (HTTPS, cookies, HSTS) ------/
# Everything here keys off IS_PROD, so a local `runserver` over plain http is
# untouched: no redirect, no secure-only cookies, no HSTS.

if IS_PROD:
    # Render terminates TLS at its edge and forwards plain http to this
    # process. Without this header Django considers every request insecure and
    # SECURE_SSL_REDIRECT would redirect forever. Only set in production —
    # trusting X-Forwarded-Proto when we are NOT behind a proxy lets any
    # client spoof "https" and defeat the checks below.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Overridable so a prod-shaped environment that is not yet on https (a first
# deploy, a health-check smoke test) can turn the redirect off deliberately.
SECURE_SSL_REDIRECT = (
    os.getenv("DJANGO_SECURE_SSL_REDIRECT", str(IS_PROD)) == "True"
)

SESSION_COOKIE_SECURE = IS_PROD
CSRF_COOKIE_SECURE = IS_PROD

# One hour to start. Raise it (31536000 = a year) once production has run
# clean on https for a while — HSTS is not revocable inside its own window.
SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS") or (3600 if IS_PROD else 0))

# Default False on purpose: this would cover media.goatza.com and every other
# subdomain, so each one must be verified reachable over https first.
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv("SECURE_HSTS_INCLUDE_SUBDOMAINS", "False") == "True"

# Preload is a one-way door (removal takes months of browser release cycles).
# Not until subdomains are covered and the max-age is a year.
SECURE_HSTS_PRELOAD = False
# ------ SECURITY END ------/


# Application definition

INSTALLED_APPS = [
    # third party apps 
    'daphne',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist', 
    'channels', 

    # my apps 
    'accounts',
    'sports',
    'organization',
    # Owns the ONE username namespace users and organizations share. Kept out
    # of both so neither app owns the other's handles.
    'usernames',
    'connections',
    'posts',
    'feed',
    'shared',
    'notifications',
    'messaging',
    'recruitments',
    'highlights',
    'careers',
    'achievements',
    'cv',
    'matches',
    'waitlist',
    'moderation',
    'legal',
    # "Report a problem" — app breakage, NOT abuse. Abuse reporting stays
    # in 'moderation'; the two share nothing but the word "report".
    'support',
    # Google Places (New) proxy. No models — it owns the API key and the daily
    # spend guard, nothing else.
    'places',

    # buildin apps 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # cors 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = "core.asgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default' : {
        'ENGINE' : 'django.db.backends.postgresql',
        'NAME' : os.getenv('DATABASE_NAME'),
        'USER' : os.getenv('DATABASE_USER'),
        'PASSWORD' : os.getenv('DATABASE_PASSWORD'),
        'HOST' : os.getenv('DATABASE_HOST'),
        'PORT' : os.getenv('DATABASE_PORT'),
        'OPTIONS': {
                # Managed Postgres (Render, Neon) requires TLS; a local
                # instance usually is not configured for it at all.
                'sslmode': os.getenv('DB_SSL_MODE') or ('require' if IS_PROD else 'disable'),
            },
        },
    }
DATABASES['default']['CONN_MAX_AGE'] = 60
DATABASES['default']['CONN_HEALTH_CHECKS'] = True

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# ------- REST FRAMEWORK -----------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    # The floor for a view that declares nothing. NOT the enforcement point:
    # a view's own permission_classes REPLACES this list rather than adding to
    # it, and every view in this app declares one (directly or through
    # core.views.base_views.BaseAPIView, which carries the same pair). This is
    # here so a view added tomorrow without a permission_classes line is closed
    # and gated by default instead of open.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        'legal.permissions.HasAcceptedCurrentTerms',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/min',    # Unauthenticated users
        'user': '100/min',   # Authenticated users
        'signup': '5/min',
        'login': '10/min',
        'otp': '5/min',
        'forgot_password': '3/hour',
        'change_password': '5/hour',
        # Account deletion, shared by BOTH /user/account/delete/ endpoints
        # (see accounts.throttles.AccountDeleteThrottle). Per USER: the account
        # belongs to the person, not to whichever actor header is on the
        # request. Tight because the honest flow is two calls and nobody
        # deletes their account twice.
        'account_delete': '3/hour',
        'message_share': '30/min',   # per actor — see messaging.throttles
        'chat_media': '30/min',      # per actor — chat photo uploads
        # Feed impression flushes (see feed.throttles). Its own scope so a long
        # scroll's telemetry never drains the shared 'user' budget that posting,
        # liking and messaging draw on.
        'feed_impressions': '60/min',
        # Public profile reads. Per IP (see core.throttles.PublicReadThrottle),
        # and generous on purpose: one shared link opening in a group chat
        # produces a burst of crawler + human hits from a handful of addresses.
        'public_profile': '60/min',
        # Joining the pre-launch waitlist — the one anonymous WRITE on
        # the public surface, so per IP and deliberately tight (see
        # waitlist.throttles.WaitlistSignupThrottle).
        'waitlist_signup': '5/hour',
        # Filing reports. Per USER, not per actor (see
        # moderation.throttles.ReportThrottle) — an actor-scoped bucket would
        # give one person a fresh ten for every org they belong to.
        'moderation_report': '10/hour',
        # "Report a problem" — app breakage, not abuse. Per USER for the same
        # reason moderation_report is (support.throttles.ProblemReportThrottle).
        'support_report': '5/hour',
        # The logged-out half, per IP and tighter: nobody legitimately files
        # three bugs an hour without a session, and everything behind that
        # route is unauthenticated and permanent
        # (support.throttles.PublicProblemReportThrottle).
        'support_report_public': '3/hour',
        # Google Places proxy (places.throttles, doc section 4.3). TWO scopes
        # per endpoint, not one: DRF resolves a single rate per scope name, so
        # the authenticated and anonymous halves of the doc's table each need
        # their own. Anonymous is tighter because the /join city picker is the
        # one place an anonymous caller can spend our Google quota.
        'places_autocomplete': '60/min',
        'places_autocomplete_anon': '20/min',
        # Details is the expensive half and is called ONCE per completed
        # search, for the prediction the user picked. A client burning through
        # this budget is calling it for the whole list.
        'places_details': '20/min',
        'places_details_anon': '10/min',
        # Recording legal consent (legal.throttles.LegalAcceptThrottle). Per
        # USER, and a day's budget: signup records consent server-side without
        # touching this endpoint, so a legitimate caller only arrives here on a
        # version bump.
        'legal_accept': '10/day',
    }
}

SIMPLE_JWT = {
    # Token lifetime
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),

    # Rotation
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Login tracking
    'UPDATE_LAST_LOGIN': True,

    # Security
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY'), 

    # Headers
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    # User
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Token behavior
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    # Extra security
    'JTI_CLAIM': 'jti',
}

# Same reasoning as the SECRET_KEY check above: SimpleJWT would happily sign
# every access token with None, and every one of them would verify.
if not SIMPLE_JWT['SIGNING_KEY']:
    raise ImproperlyConfigured(
        "JWT_SECRET_KEY is not set. Set it to a long random string in the "
        "environment (or .env for local development)."
    )
# ------- REST FRAMEWORKS END ------/



# ------ CORS ------------/
# Both lists come from the environment, comma-separated, so the deployed
# origins are never baked into source control. Local dev needs neither var set.
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", "http://localhost:3000")

# The Vercel frontend origin (https://goatza.com) belongs in CORS_ALLOWED_ORIGINS
# in production. The browser rarely needs it: NEXT_PUBLIC_API_URL is the "/api"
# Vercel rewrite, so calls are same-origin and proxied. It still matters for
# direct calls (a preview build pointed at this API) and it must stay in step
# with NEXT_PUBLIC_SITE_URL — that value is what the public profile's canonical
# and Open Graph URLs are built from.
CORS_ALLOWED_ORIGINS = env_list("CORS_ALLOWED_ORIGINS", "http://localhost:3000")

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-actor-type',  
    'x-actor-id',  
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
# ------ CORS END --------/



# ------ MEDIA STORAGE ------ /
# The only backend services/storage/factory.py knows how to hand out. Kept as a
# setting rather than dropped so an environment still carrying an old value
# fails loudly in the factory instead of uploading somewhere unexpected.
#
# `or` instead of getenv's default argument throughout this block: the keys ship
# in .env with empty values, and getenv would hand back "" — an empty provider
# raises, and an empty base URL would make is_valid_media_url() accept literally
# any URL.
FILE_STORAGE_PROVIDER = os.getenv("FILE_STORAGE_PROVIDER") or "r2"


# ------ CLOUDFLARE R2 (media) ------ /
# S3-compatible. The browser uploads straight to the bucket with a presigned
# PUT, so these credentials never leave the server and files never touch the app.
R2_ACCOUNT_ID = os.getenv("R2_ACCOUNT_ID")
R2_ACCESS_KEY_ID = os.getenv("R2_ACCESS_KEY_ID")
R2_SECRET_ACCESS_KEY = os.getenv("R2_SECRET_ACCESS_KEY")
R2_BUCKET = os.getenv("R2_BUCKET") or "goatza-media"

# Public delivery origin, NO trailing slash: a stored URL is this + "/" + key.
# Production is the CDN domain in front of the bucket; local dev points at the
# bucket's r2.dev URL.
MEDIA_PUBLIC_BASE_URL = (
    os.getenv("MEDIA_PUBLIC_BASE_URL") or "https://media.goatza.com"
).rstrip("/")



# -------- EMAIL CONFIG ----------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


RESEND_API_KEY = os.getenv('RESEND_API_KEY')
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL')


# ------- GOOGLE LOGIN ---------
GOOGLE_AUTH_CLIENT_ID = os.getenv('GOOGLE_AUTH_CLIENT_ID')
GOOGLE_AUTH_CLIENT_SECRET = os.getenv('GOOGLE_AUTH_CLIENT_SECRET')
GOOGLE_AUTH_SCOPE = os.getenv('GOOGLE_AUTH_SCOPE')
GOOGLE_CALLBACK_URI = os.getenv('GOOGLE_CALLBACK_URI')



# ------- firebase config -------
FIREBASE_PROJECT_ID = os.getenv("FIREBASE_PROJECT_ID")
FIREBASE_PRIVATE_KEY_ID = os.getenv("FIREBASE_PRIVATE_KEY_ID")
FIREBASE_PRIVATE_KEY = os.getenv("FIREBASE_PRIVATE_KEY")
FIREBASE_CLIENT_EMAIL = os.getenv("FIREBASE_CLIENT_EMAIL")
FIREBASE_CLIENT_ID = os.getenv("FIREBASE_CLIENT_ID")


# --------- REDIS CHANNEL --------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL")],
        },
    },
}


# ------ CACHE (auth refresh grace window + general) ------/
_REDIS_URL = os.getenv("REDIS_URL")
if _REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
# ------ CACHE END ------/

AUTH_COOKIE_DOMAIN = os.getenv("AUTH_COOKIE_DOMAIN")  # None = host-only

# ------ WAITLIST (pre-launch player registration) ------/

# Where the "somebody just signed up" mail goes. No default: an address in
# source control is an address that keeps receiving mail from every fork,
# staging box and local run. Unset simply means the notification is skipped
# (waitlist.services.signup_services logs it) — the signup itself still lands.
WAITLIST_NOTIFY_EMAIL = os.getenv("WAITLIST_NOTIFY_EMAIL")

# The number the landing page counts towards. A setting because it is a
# marketing target that moves the moment it is hit.
WAITLIST_GOAL = int(os.getenv("WAITLIST_GOAL", "1000"))

# Presentation-only head start on the public numbers.
#
# The first real signup should read as #37 rather than #1: a counter that says
# "0 players joined" is a page that tells its first visitor to come back later.
# The DATABASE stays honest — signup_number is a dense sequence from 1 — and
# the offset is added in exactly one place (waitlist.selectors.display_number),
# so the counter, the number on the success screen and the number on the share
# card can never disagree with each other.
#
# FIX THIS BEFORE GO-LIVE. ref_code is derived from the DISPLAY number and then
# PERSISTED, so raising the offset after real signups exist leaves old codes
# pointing at numbers nobody will be shown again.
WAITLIST_DISPLAY_OFFSET = int(os.environ.get("WAITLIST_DISPLAY_OFFSET", 36))
# ------ WAITLIST END ------/

# ------ MODERATION (reports) ------/

# Where a PRIORITY report alert goes — minor_safety, self_harm and violence
# only. Empty means the mail is skipped and the report still lands; an address
# baked into source control is an address that keeps receiving mail from every
# fork, staging box and local run (same reasoning as WAITLIST_NOTIFY_EMAIL).
#
# Deliberately not every category. A spam report at 3am is not worth a
# notification; the admin queue is where those get seen.
MODERATION_ALERT_EMAIL = os.getenv("MODERATION_ALERT_EMAIL", "")

# Origin the alert's "Review it" link is built against, e.g.
# https://api.goatza.com. Empty leaves the link RELATIVE
# (/admin/moderation/report/<id>/change/), which is right for a local run and
# harmless in mail — better a path than an absolute URL pointing at the wrong
# environment.
SITE_ADMIN_BASE_URL = os.getenv("SITE_ADMIN_BASE_URL", "")
# ------ MODERATION END ------/

# ------ GOOGLE PLACES (city + venue search) ------/
# The proxy in places/ is the ONLY thing that talks to Google. The key is
# server-side and never reaches the browser (docs/PLACES_MIGRATION.md decision
# 2), which is the whole reason the proxy exists.

# Unset is a supported state: the app boots normally and the two /places/
# endpoints answer 503 with a logged warning, so a checkout with no key still
# runs everything that is not place search.
GOOGLE_PLACES_API_KEY = os.getenv("GOOGLE_PLACES_API_KEY")

# The INNER spend backstop, per UTC day, per SKU. Google console quotas are the
# outer one — this is the one that can answer with a friendly 503 instead of a
# dead picker, and it stops the call before it is billed. `or` rather than
# getenv's default argument for the same reason as the R2 block above: the keys
# ship in .env with empty values, and int("") raises at import, which would
# take the whole app down over a blank line in an env file.
#
# Details and the coordinate-refresh job SHARE the details cap: same endpoint,
# same SKU, same money.
PLACES_DAILY_CAP_AUTOCOMPLETE = int(
    os.getenv("PLACES_DAILY_CAP_AUTOCOMPLETE") or 2000
)
PLACES_DAILY_CAP_DETAILS = int(os.getenv("PLACES_DAILY_CAP_DETAILS") or 1000)

# The city picker's type filter, comma-separated. A SETTING rather than a
# constant because which small towns Google classifies as a "city" is not
# stable and widening the list must not need a deploy: `(cities)` (= locality +
# administrative_area_level_3) covers Thalassery, Panoor and Kuthuparamba, but
# a village that goes missing is fixed by setting e.g.
# "locality,sublocality,neighborhood,administrative_area_level_3,administrative_area_level_4".
# Google allows at most 5 values and refuses to mix a collection like
# `(cities)` with individual types.
PLACES_CITY_PRIMARY_TYPES = os.getenv("PLACES_CITY_PRIMARY_TYPES") or "(cities)"

# ---- Coordinate lifecycle ("B-lite", doc section 6) ----
# We may keep a place_id forever but not its coordinates, so a Location's point
# is a cache with an expiry. REFRESH re-fetches a place something still depends
# on; EXPIRE nulls the coordinates of one nothing does. The gap between the two
# is the safety margin: refresh at 25 days so a place has five days of runs to
# be caught before the 30-day expiry drops it.
PLACES_COORDS_REFRESH_AFTER_DAYS = int(
    os.getenv("PLACES_COORDS_REFRESH_AFTER_DAYS") or 25
)
PLACES_COORDS_EXPIRE_AFTER_DAYS = int(
    os.getenv("PLACES_COORDS_EXPIRE_AFTER_DAYS") or 30
)

# What counts as an "active user" for the refresh job: last_login OR
# profile.updated_at inside this window. Both, because refresh tokens rotate
# for thirty days without touching last_login.
PLACES_ACTIVE_USER_DAYS = int(os.getenv("PLACES_ACTIVE_USER_DAYS") or 30)
# ------ GOOGLE PLACES END ------/

# ------ LOGGING ------/
# One console handler on stdout: Render captures a process's stdout as its log
# stream, and locally it is just the terminal. No file handler — a container's
# filesystem is ephemeral and nothing would ever read it.
#
# The app loggers (logging.getLogger(__name__) across accounts/, posts/,
# services/ ...) are deliberately NOT listed: they inherit the root logger, so
# every existing call starts emitting without a per-app entry here.
LOGGING = {
    "version": 1,
    # False, so anything configured before this dict is read (Django's own
    # bootstrap loggers, a library's) keeps working instead of going silent.
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "{levelname} {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": sys.stdout,
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": os.getenv("LOG_LEVEL", "INFO"),
    },
    "loggers": {
        # Framework chatter at INFO regardless of how loud LOG_LEVEL is set.
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        # 4xx/5xx only. At INFO this logs a line for every handled request.
        "django.request": {
            "handlers": ["console"],
            "level": "WARNING",
            "propagate": False,
        },
        # The runserver access log. Kept at INFO so local development still
        # shows the familiar "GET /api/... 200" lines; in production gunicorn
        # or daphne does the access logging and this logger stays quiet.
        "django.server": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}
# ------ LOGGING END ------/


# ------ SENTRY (error reporting) ------/
# Guarded on the DSN, not on IS_PROD: unset means nothing initializes, which is
# the normal state on localhost and in CI. Setting the DSN in a staging
# environment is enough to turn it on there.
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN:
    import sentry_sdk

    _sentry_options = {
        "dsn": SENTRY_DSN,
        # Performance tracing off by default — it is sampled per transaction
        # and the free tier's quota is spent on errors, not traces.
        "traces_sample_rate": float(os.getenv("SENTRY_TRACES_SAMPLE_RATE") or 0.0),
        # No emails, usernames or IPs attached to events. This app's users are
        # athletes, many of them minors; an error report is not a place for
        # their identifiers.
        "send_default_pii": False,
        "environment": "production" if IS_PROD else "development",
    }

    # Render injects the deployed commit SHA. With it, an issue points at the
    # exact code that raised instead of "whatever was live at the time".
    _sentry_release = os.getenv("RENDER_GIT_COMMIT")
    if _sentry_release:
        _sentry_options["release"] = _sentry_release

    sentry_sdk.init(**_sentry_options)
# ------ SENTRY END ------/
