"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 6.0.3.
"""

import os 
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    # third party apps 
    'daphne',
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist', 
    'cloudinary',
    'cloudinary_storage', 
    'channels', 

    # my apps 
    'accounts',
    'sports',
    'organization',
    'connections',
    'posts',
    'feed',
    'shared',
    'notifications',
    'messaging',
    'recruitments',
    'highlights',
    'careers',
    'achievements',
    'cv',
    'matches',
    'waitlist',

    # buildin apps 
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # cors 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = "core.asgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default' : {
        'ENGINE' : 'django.db.backends.postgresql',
        'NAME' : os.getenv('DATABASE_NAME'),
        'USER' : os.getenv('DATABASE_USER'),
        'PASSWORD' : os.getenv('DATABASE_PASSWORD'),
        'HOST' : os.getenv('DATABASE_HOST'),
        'PORT' : os.getenv('DATABASE_PORT'),
        'OPTIONS': {
                'sslmode': os.getenv('DB_SSL_MODE', 'disable'),
            },
        },
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = "accounts.User"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'

# ------- REST FRAMEWORK -----------

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '20/min',    # Unauthenticated users
        'user': '100/min',   # Authenticated users
        'signup': '5/min',
        'login': '10/min',
        'otp': '5/min',
        'forgot_password': '3/hour',
        'change_password': '5/hour',
        'message_share': '30/min',   # per actor — see messaging.throttles
        'chat_media': '30/min',      # per actor — chat photo uploads
        # Feed impression flushes (see feed.throttles). Its own scope so a long
        # scroll's telemetry never drains the shared 'user' budget that posting,
        # liking and messaging draw on.
        'feed_impressions': '60/min',
        # Public profile reads. Per IP (see core.throttles.PublicReadThrottle),
        # and generous on purpose: one shared link opening in a group chat
        # produces a burst of crawler + human hits from a handful of addresses.
        'public_profile': '60/min',
        # Joining the pre-launch waitlist — the one anonymous WRITE on
        # the public surface, so per IP and deliberately tight (see
        # waitlist.throttles.WaitlistSignupThrottle).
        'waitlist_signup': '5/hour',
    }
}

SIMPLE_JWT = {
    # Token lifetime
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),

    # Rotation
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,

    # Login tracking
    'UPDATE_LAST_LOGIN': True,

    # Security
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': os.getenv('JWT_SECRET_KEY'), 

    # Headers
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',

    # User
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    # Token behavior
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    # Extra security
    'JTI_CLAIM': 'jti',
}
# ------- REST FRAMEWORKS END ------/



# ------ CORS ------------/
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "https://goatza-backend.onrender.com",
    "https://goatza.com",
]

# for production
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

# The Vercel frontend origin (https://goatza.com) is listed here. In production
# the browser rarely needs it: NEXT_PUBLIC_API_URL is the "/api" Vercel rewrite,
# so calls are same-origin and proxied. It still matters for direct calls
# (a preview build pointed at this API) and it must stay in step with
# NEXT_PUBLIC_SITE_URL — that value is what the public profile's canonical and
# Open Graph URLs are built from.
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://goatza-backend.onrender.com",
    "https://goatza.com",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'x-actor-type',  
    'x-actor-id',  
]

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]
# ------ CORS END --------/



# ------ CLOUDINARY (media) ------ /
CLOUDINARY_CLOUD_NAME = os.getenv("CLOUDINARY_CLOUD_NAME")
CLOUDINARY_API_KEY = os.getenv("CLOUDINARY_API_KEY")
CLOUDINARY_API_SECRET = os.getenv("CLOUDINARY_API_SECRET")

# Generate the HLS adaptive-streaming ladder alongside the mp4 derivative.
# Off by default: streaming profiles cost meaningfully more transformation
# credits than the single mp4, which burns through the free tier during
# development. The frontend has a matching flag, NEXT_PUBLIC_ENABLE_HLS.
CLOUDINARY_ENABLE_HLS = os.getenv("CLOUDINARY_ENABLE_HLS", "False") == "True"

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': CLOUDINARY_CLOUD_NAME,
    'API_KEY': CLOUDINARY_API_KEY,
    'API_SECRET': CLOUDINARY_API_SECRET,
}

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'



# -------- EMAIL CONFIG ----------
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER


RESEND_API_KEY = os.getenv('RESEND_API_KEY')
RESEND_FROM_EMAIL = os.getenv('RESEND_FROM_EMAIL')


# ------- GOOGLE LOGIN ---------
GOOGLE_AUTH_CLIENT_ID = os.getenv('GOOGLE_AUTH_CLIENT_ID')
GOOGLE_AUTH_CLIENT_SECRET = os.getenv('GOOGLE_AUTH_CLIENT_SECRET')
GOOGLE_AUTH_SCOPE = os.getenv('GOOGLE_AUTH_SCOPE')
GOOGLE_CALLBACK_URI = os.getenv('GOOGLE_CALLBACK_URI')



# ------- firebase config -------
FIREBASE_PROJECT_ID = os.getenv("FIREBASE_PROJECT_ID")
FIREBASE_PRIVATE_KEY_ID = os.getenv("FIREBASE_PRIVATE_KEY_ID")
FIREBASE_PRIVATE_KEY = os.getenv("FIREBASE_PRIVATE_KEY")
FIREBASE_CLIENT_EMAIL = os.getenv("FIREBASE_CLIENT_EMAIL")
FIREBASE_CLIENT_ID = os.getenv("FIREBASE_CLIENT_ID")


# --------- REDIS CHANNEL --------
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [os.getenv("REDIS_URL")],
        },
    },
}


# ------ CACHE (auth refresh grace window + general) ------/
_REDIS_URL = os.getenv("REDIS_URL")
if _REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.redis.RedisCache",
            "LOCATION": _REDIS_URL,
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        }
    }
# ------ CACHE END ------/

AUTH_COOKIE_DOMAIN = os.getenv("AUTH_COOKIE_DOMAIN")  # None = host-only

# ------ WAITLIST (pre-launch player registration) ------/

# Where the "somebody just signed up" mail goes. No default: an address in
# source control is an address that keeps receiving mail from every fork,
# staging box and local run. Unset simply means the notification is skipped
# (waitlist.services.signup_services logs it) — the signup itself still lands.
WAITLIST_NOTIFY_EMAIL = os.getenv("WAITLIST_NOTIFY_EMAIL")

# The number the landing page counts towards. A setting because it is a
# marketing target that moves the moment it is hit.
WAITLIST_GOAL = int(os.getenv("WAITLIST_GOAL", "1000"))

# Presentation-only head start on the public numbers.
#
# The first real signup should read as #37 rather than #1: a counter that says
# "0 players joined" is a page that tells its first visitor to come back later.
# The DATABASE stays honest — signup_number is a dense sequence from 1 — and
# the offset is added in exactly one place (waitlist.selectors.display_number),
# so the counter, the number on the success screen and the number on the share
# card can never disagree with each other.
#
# FIX THIS BEFORE GO-LIVE. ref_code is derived from the DISPLAY number and then
# PERSISTED, so raising the offset after real signups exist leaves old codes
# pointing at numbers nobody will be shown again.
WAITLIST_DISPLAY_OFFSET = int(os.environ.get("WAITLIST_DISPLAY_OFFSET", 36))
# ------ WAITLIST END ------/
