# Generated by Django 6.0.3 on 2026-09-01 07:57

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0011_organizationlocation_location'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(editable=False, max_length=12, unique=True)),
                ('category', models.CharField(choices=[('not_working', "Something isn't working"), ('display_issue', 'Looks broken or misplaced'), ('performance', 'Slow or keeps crashing'), ('account_login', 'Login or account issue'), ('media_upload', "Media won't upload or play"), ('suggestion', 'Suggestion or feedback'), ('other', 'Something else')], max_length=30)),
                ('description', models.TextField()),
                ('screenshots', models.JSONField(blank=True, default=list)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('client_context', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('new', 'New'), ('triaged', 'Triaged'), ('resolved', 'Resolved'), ('wont_fix', "Won't fix"), ('duplicate', 'Duplicate'), ('spam_suspect', 'Spam suspect')], db_index=True, default='new', max_length=20)),
                ('internal_note', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acting_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports', to='organization.organization')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='problem_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'problem_reports',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='problem_rep_status_4e855e_idx'), models.Index(fields=['reported_by'], name='problem_rep_reporte_8765e9_idx'), models.Index(fields=['reference'], name='problem_rep_referen_10d1d7_idx')],
            },
        ),
    ]
