# Generated by Django 6.0.3 on 2026-05-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organizationprofile_following_count'),
        ('recruitments', '0001_initial'),
        ('shared', '0001_initial'),
        ('sports', '0004_alter_sport_icon_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recruitment',
            name='recruitment_valid_age_range',
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('min_age__isnull', True), ('max_age__isnull', True), ('min_age__lte', models.F('max_age')), _connector='OR'), name='recruitment_valid_age_range'),
        ),
    ]
