# Generated by Django 6.0.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0005_alter_recruitmentmedia_file_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='shared_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='shared_email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='shared_phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
