# Generated by Django 6.0.3 on 2026-08-09 09:55

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0006_recruitmentapplication_shared_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentEligibilityCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recruitment_eligibility_criteria',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='age_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='recruitments.recruitmentagecategory'),
        ),
        migrations.AlterField(
            model_name='recruitmentagecategory',
            name='max_birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recruitmentagecategory',
            name='min_birth_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='recruitmentagecategory',
            constraint=models.CheckConstraint(condition=models.Q(('min_birth_year__isnull', False), ('max_birth_year__isnull', False), _connector='OR'), name='age_category_birth_year_required'),
        ),
        migrations.AddField(
            model_name='recruitmenteligibilitycriteria',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_criteria', to='recruitments.recruitment'),
        ),
        migrations.AddIndex(
            model_name='recruitmenteligibilitycriteria',
            index=models.Index(fields=['recruitment'], name='recruitment_recruit_911e24_idx'),
        ),
    ]
