# Generated by Django 6.0.3 on 2026-08-12 18:20

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0007_recruitmenteligibilitycriteria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentDiscoverImpression',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('recommended', 'Recommended'), ('closing_soon', 'Closing Soon'), ('near_you', 'Near You'), ('new_this_week', 'New This Week')], max_length=20)),
                ('match_score', models.FloatField()),
                ('is_eligible', models.BooleanField(default=True)),
                ('served_count', models.PositiveIntegerField(default=1)),
                ('first_served_at', models.DateTimeField()),
                ('last_served_at', models.DateTimeField()),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discover_impressions', to='recruitments.recruitment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recruitment_discover_impressions',
                'indexes': [models.Index(fields=['recruitment', 'section'], name='recruitment_recruit_8b9666_idx'), models.Index(fields=['user', 'last_served_at'], name='recruitment_user_id_537539_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recruitment', 'section'), name='unique_discover_impression')],
            },
        ),
    ]
