# Generated by Django 6.0.3 on 2026-09-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0010_savedrecruitment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruitment',
            old_name='shortlisted_count',
            new_name='confirmed_count',
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='age_mismatch_at_apply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('invited', 'Invited'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('trial_confirmed', 'Trial Confirmed'), ('not_shortlisted', 'Not Shortlisted'), ('not_selected', 'Not Selected')], db_index=True, default='applied', max_length=30),
        ),
    ]
