# Generated by Django 6.0.3 on 2026-09-24 05:28

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0011_rename_shortlisted_count_recruitment_confirmed_count_and_more'),
        ('shared', '0002_remove_location_unique_external_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='session_mode',
            field=models.CharField(choices=[('all', 'Attend every date'), ('choose_one', 'Pick one date')], default='all', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='trial_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TrialSession',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=120)),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('venue_name', models.CharField(blank=True, max_length=255)),
                ('venue_link', models.URLField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trial_sessions', to='shared.location')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='recruitments.recruitment')),
            ],
            options={
                'db_table': 'recruitment_trial_sessions',
                'ordering': ['date', 'start_time', 'display_order'],
            },
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='recruitments.trialsession'),
        ),
        migrations.AddIndex(
            model_name='trialsession',
            index=models.Index(fields=['recruitment'], name='recruitment_recruit_de085f_idx'),
        ),
    ]
