# Generated by Django 6.0.3 on 2026-09-24 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationlocation_location'),
        ('recruitments', '0012_recruitment_session_mode_recruitment_trial_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='attendance_closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='attendance_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='auto_confirm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='fee_marked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_marked_applications', to='organization.organizationmember'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='fee_paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
