# Generated by Django 6.0.3 on 2026-09-24 09:38

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationlocation_location'),
        ('recruitments', '0013_recruitment_attendance_closed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentAnnouncement',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(max_length=1000)),
                ('audience', models.CharField(choices=[('all_applicants', 'All applicants'), ('confirmed', 'Everyone called to the trial'), ('selected', 'Selected players')], max_length=20)),
                ('recipients_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to='organization.organizationmember')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='recruitments.recruitment')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcements', to='recruitments.trialsession')),
            ],
            options={
                'db_table': 'recruitment_announcements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('notification', 'In-app + push'), ('email', 'Email'), ('dm', 'Goatza message')], max_length=15)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=255)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_deliveries', to='recruitments.recruitmentapplication')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_deliveries', to=settings.AUTH_USER_MODEL)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='recruitments.recruitmentannouncement')),
            ],
            options={
                'db_table': 'recruitment_announcement_deliveries',
            },
        ),
        migrations.AddIndex(
            model_name='recruitmentannouncement',
            index=models.Index(fields=['recruitment', '-created_at'], name='recruitment_recruit_ab8119_idx'),
        ),
        migrations.AddIndex(
            model_name='announcementdelivery',
            index=models.Index(fields=['state', 'created_at'], name='recruitment_state_c584e5_idx'),
        ),
        migrations.AddConstraint(
            model_name='announcementdelivery',
            constraint=models.UniqueConstraint(fields=('announcement', 'application', 'channel'), name='unique_announcement_delivery'),
        ),
    ]
