# Generated by Django 6.0.3 on 2026-09-24 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationlocation_location'),
        ('recruitments', '0014_recruitmentannouncement_announcementdelivery_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='announcementdelivery',
            name='unique_announcement_delivery',
        ),
        migrations.AddField(
            model_name='announcementdelivery',
            name='created_by_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_deliveries', to='organization.organizationmember'),
        ),
        migrations.AddField(
            model_name='announcementdelivery',
            name='direct_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='trial_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcementdelivery',
            name='announcement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='recruitments.recruitmentannouncement'),
        ),
        migrations.AddConstraint(
            model_name='announcementdelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('announcement__isnull', False)), fields=('announcement', 'application', 'channel'), name='unique_announcement_delivery'),
        ),
    ]
