# Generated by Django 6.0.3 on 2026-09-24 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationlocation_location'),
        ('recruitments', '0015_remove_announcementdelivery_unique_announcement_delivery_and_more'),
        ('sports', '0004_alter_sport_icon_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='attendance_status',
            field=models.CharField(blank=True, choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='attended_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attended_applications', to='recruitments.trialsession'),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='check_in_code',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='check_in_method',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('code', 'Code')], max_length=10),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='checked_in_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='checked_in_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_in_applications', to='organization.organizationmember'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('check_in_code', ''), _negated=True), fields=('recruitment', 'check_in_code'), name='unique_check_in_code'),
        ),
    ]
