# Generated by Django 6.0.3 on 2026-09-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0016_recruitmentapplication_attendance_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitment',
            name='recruitment_type',
            field=models.CharField(choices=[('open_trial', 'Open Trial'), ('player_looking', 'Player Looking')], max_length=30),
        ),
        migrations.AlterField(
            model_name='recruitmentapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('selected', 'Selected'), ('withdrawn', 'Withdrawn'), ('trial_confirmed', 'Trial Confirmed'), ('not_shortlisted', 'Not Shortlisted'), ('not_selected', 'Not Selected')], db_index=True, default='applied', max_length=30),
        ),
    ]
