# Generated by Django 6.0.3 on 2026-09-24 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationlocation_location'),
        ('recruitments', '0017_alter_recruitment_recruitment_type_and_more'),
        ('sports', '0004_alter_sport_icon_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recruitmentapplication',
            name='unique_check_in_code',
        ),
        migrations.RenameField(
            model_name='recruitmentapplication',
            old_name='check_in_code',
            new_name='pass_code',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='attendance_closed_at',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='attendance_enabled',
        ),
        migrations.AddConstraint(
            model_name='recruitmentapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('pass_code', ''), _negated=True), fields=('recruitment', 'pass_code'), name='unique_pass_code'),
        ),
        migrations.RemoveField(
            model_name='recruitmentapplication',
            name='attendance_status',
        ),
        migrations.RemoveField(
            model_name='recruitmentapplication',
            name='attended_session',
        ),
        migrations.RemoveField(
            model_name='recruitmentapplication',
            name='check_in_method',
        ),
        migrations.RemoveField(
            model_name='recruitmentapplication',
            name='checked_in_at',
        ),
        migrations.RemoveField(
            model_name='recruitmentapplication',
            name='checked_in_by',
        ),
    ]
