# Generated by Django 6.0.3 on 2026-09-24 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0018_remove_attendance_rename_pass_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentapplication',
            name='attended_self_reported',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='feedback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='outcome_self_reported',
            field=models.CharField(blank=True, choices=[('selected', 'Selected'), ('not_selected', 'Not selected'), ('waiting', 'Still waiting to hear')], max_length=15),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='trial_feedback',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='recruitmentapplication',
            name='trial_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
