# Generated by Django 6.0.3 on 2026-09-25 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0019_trial_self_report'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recruitmentdiscoverimpression',
            name='recruitment_recruit_8b9666_idx',
        ),
        migrations.RemoveIndex(
            model_name='recruitmentdiscoverimpression',
            name='recruitment_user_id_537539_idx',
        ),
        migrations.RemoveConstraint(
            model_name='recruitmentdiscoverimpression',
            name='unique_discover_impression',
        ),
        migrations.DeleteModel(
            name='RecruitmentDiscoverImpression',
        ),
    ]
