# Generated by Django 6.0.3 on 2026-10-05 18:17
# Recruitment.timezone — the calendar THIS trial runs on, copied from the
# organization at create time and editable afterwards. Pairs with
# organization/0012.
#
# NO DATA MIGRATION AND NO BACKFILL: the default is
# settings.RECRUITMENT_TIMEZONE, which is the zone every stored event_date and
# trial_end_date was already derived in, so existing rows are consistent by
# construction.


import utils.timezones
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0020_drop_discover_impressions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='timezone',
            field=models.CharField(default=utils.timezones.default_timezone, max_length=64, validators=[utils.timezones.validate_timezone]),
        ),
    ]
