# Generated by Django 6.0.3 on 2026-10-06 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0021_recruitment_timezone'),
        ('shared', '0002_remove_location_unique_external_location_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='trialsession',
            index=models.Index(fields=['latitude', 'longitude'], name='recruitment_latitud_82e49c_idx'),
        ),
    ]
