# Generated by Django 6.0.3 on 2026-10-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0022_trialsession_coords_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitmentagecategory',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='recruitmentagecategory',
            name='sessions',
            field=models.ManyToManyField(blank=True, related_name='age_categories', to='recruitments.trialsession'),
        ),
    ]
