# Generated by Django 6.0.3 on 2026-08-06 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Forwarding a profile into a chat: two message types, two FKs.

    The constraint is dropped and rebuilt rather than added alongside. It is a
    single CheckConstraint whose every branch asserts that *every other* shared
    FK is null, so adding two columns rewrites all three existing branches —
    there is no version of this that appends. RemoveConstraint has to come
    before the AddFields, or the new columns would briefly exist under a rule
    that doesn't mention them.

    ``message_type`` is still max_length=20; the longer of the two new values
    ("shared_user_profile") is 19.
    """

    dependencies = [
        ('messaging', '0003_message_media_duration_ms_message_media_height_and_more'),
        ('organization', '0008_organizationprofile_is_public_profile'),
        ('posts', '0011_remove_savedpost_unique_saved_post_savedpost_org_and_more'),
        ('recruitments', '0006_recruitmentapplication_shared_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_shared_object_matches_type',
        ),
        migrations.AddField(
            model_name='message',
            name='shared_profile_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='message',
            name='shared_profile_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('system', 'System'), ('shared_post', 'Shared Post'), ('shared_recruitment', 'Shared Recruitment'), ('shared_user_profile', 'Shared User Profile'), ('shared_org_profile', 'Shared Organization Profile')], default='text', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shared_post__isnull', True), ('shared_profile_org__isnull', True), ('shared_profile_user__isnull', True), ('shared_recruitment__isnull', True)), models.Q(('message_type', 'shared_post'), ('shared_post__isnull', False), ('shared_profile_org__isnull', True), ('shared_profile_user__isnull', True), ('shared_recruitment__isnull', True)), models.Q(('message_type', 'shared_recruitment'), ('shared_post__isnull', True), ('shared_profile_org__isnull', True), ('shared_profile_user__isnull', True), ('shared_recruitment__isnull', False)), models.Q(('message_type', 'shared_user_profile'), ('shared_post__isnull', True), ('shared_profile_org__isnull', True), ('shared_profile_user__isnull', False), ('shared_recruitment__isnull', True)), models.Q(('message_type', 'shared_org_profile'), ('shared_post__isnull', True), ('shared_profile_org__isnull', False), ('shared_profile_user__isnull', True), ('shared_recruitment__isnull', True)), _connector='OR'), name='message_shared_object_matches_type'),
        ),
    ]
