# Generated by Django 6.0.3 on 2026-05-09 06:11

import django.core.validators
import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0006_organizationprofile_following_count'),
        ('shared', '0001_initial'),
        ('sports', '0004_alter_sport_icon_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruitment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('recruitment_type', models.CharField(choices=[('open_trial', 'Open Trial'), ('player_looking', 'Player Looking'), ('direct_recruitment', 'Direct Recruitment'), ('scholarship', 'Scholarship')], max_length=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('followers_only', 'Followers Only'), ('private', 'Private')], default='public', max_length=30)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('all', 'All')], max_length=10)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(100)])),
                ('experience_level', models.CharField(blank=True, max_length=50)),
                ('application_deadline', models.DateTimeField(blank=True, null=True)),
                ('event_date', models.DateTimeField(blank=True, null=True)),
                ('is_remote', models.BooleanField(default=False)),
                ('max_applications', models.PositiveIntegerField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fee_currency', models.CharField(default='INR', max_length=10)),
                ('payment_note', models.CharField(blank=True, max_length=255)),
                ('location_name', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country_code', models.CharField(blank=True, max_length=5)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('applications_count', models.PositiveIntegerField(default=0)),
                ('shortlisted_count', models.PositiveIntegerField(default=0)),
                ('selected_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recruitments', to='organization.organizationmember')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recruitments', to='shared.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='organization.organization')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='sports.sport')),
            ],
            options={
                'db_table': 'recruitments',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentApplication',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True)),
                ('highlight_video_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('invited', 'Invited'), ('selected', 'Selected'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], db_index=True, default='applied', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitment_applications', to=settings.AUTH_USER_MODEL)),
                ('applied_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='sports.sportposition')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitments.recruitment')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to='organization.organizationmember')),
            ],
            options={
                'db_table': 'recruitment_applications',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentApplicationStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='recruitments.recruitmentapplication')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.organizationmember')),
            ],
            options={
                'db_table': 'recruitment_application_status_history',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentMedia',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=10)),
                ('file_url', models.URLField()),
                ('public_id', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='recruitments.recruitment')),
            ],
            options={
                'db_table': 'recruitment_media',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentPosition',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruitments', to='sports.sportposition')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='recruitments.recruitment')),
            ],
            options={
                'db_table': 'recruitment_positions',
            },
        ),
        migrations.CreateModel(
            name='RecruitmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('short_text', 'Short Text'), ('long_text', 'Long Text'), ('select', 'select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('number', 'Number')], max_length=30)),
                ('is_required', models.BooleanField(default=False)),
                ('placeholder', models.CharField(blank=True, max_length=255)),
                ('help_text', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='recruitments.recruitment')),
            ],
            options={
                'db_table': 'recruitment_questions',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='recruitments.recruitmentquestion')),
            ],
            options={
                'db_table': 'recruitment_question_options',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentApplicationAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('answer_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recruitments.recruitmentapplication')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='recruitments.recruitmentquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitments.recruitmentquestionoption')),
            ],
            options={
                'db_table': 'recruitment_application_answers',
            },
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['organization'], name='recruitment_organiz_a5631b_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['sport'], name='recruitment_sport_i_5026bb_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['published_at'], name='recruitment_publish_ed64f3_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['event_date'], name='recruitment_event_d_4a84e1_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitment',
            index=models.Index(fields=['latitude', 'longitude'], name='recruitment_latitud_5e91ae_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('min_age__lte', models.F('max_age'))), name='recruitment_valid_age_range'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fee_amount__isnull', True), ('is_paid', False)), models.Q(('fee_amount__isnull', False), ('is_paid', True)), _connector='OR'), name='recruitment_valid_fee'),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(('event_date__isnull', True), ('application_deadline__isnull', True), ('application_deadline__lte', models.F('event_date')), _connector='OR'), name='valid_application_deadline'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['recruitment'], name='recruitment_recruit_9f397c_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['applicant'], name='recruitment_applica_86c7bb_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['status'], name='recruitment_status_905269_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['-applied_at'], name='recruitment_applied_707640_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplication',
            index=models.Index(fields=['recruitment', 'status'], name='recruitment_recruit_0aabda_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentapplication',
            constraint=models.UniqueConstraint(fields=('recruitment', 'applicant'), name='unique_recruitment_application'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplicationstatushistory',
            index=models.Index(fields=['application'], name='recruitment_applica_882a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplicationstatushistory',
            index=models.Index(fields=['created_at'], name='recruitment_created_6c9fe0_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentmedia',
            index=models.Index(fields=['recruitment'], name='recruitment_recruit_2748c5_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentposition',
            index=models.Index(fields=['recruitment'], name='recruitment_recruit_0fe085_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentposition',
            index=models.Index(fields=['position'], name='recruitment_positio_68d145_idx'),
        ),
        migrations.AddConstraint(
            model_name='recruitmentposition',
            constraint=models.UniqueConstraint(fields=('recruitment', 'position'), name='unique_recruitment_position'),
        ),
        migrations.AddIndex(
            model_name='recruitmentquestion',
            index=models.Index(fields=['recruitment'], name='recruitment_recruit_078017_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentquestionoption',
            index=models.Index(fields=['question'], name='recruitment_questio_8c1f4d_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplicationanswer',
            index=models.Index(fields=['application'], name='recruitment_applica_43acfe_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentapplicationanswer',
            index=models.Index(fields=['question'], name='recruitment_questio_1de4c7_idx'),
        ),
    ]
