# Generated by Django 6.0.3 on 2026-05-16 10:13

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_organizationprofile_following_count'),
        ('recruitments', '0002_remove_recruitment_recruitment_valid_age_range_and_more'),
        ('shared', '0001_initial'),
        ('sports', '0004_alter_sport_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentAgeCategory',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('min_birth_year', models.PositiveIntegerField()),
                ('max_birth_year', models.PositiveIntegerField()),
                ('reporting_time', models.TimeField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recruitment_age_categories',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentContact',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('contact_type', models.CharField(choices=[('phone', 'Phone'), ('email', 'Email')], max_length=20)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'recruitment_contacts',
            },
        ),
        migrations.RemoveConstraint(
            model_name='recruitment',
            name='recruitment_valid_age_range',
        ),
        migrations.AddField(
            model_name='recruitment',
            name='apply_method',
            field=models.CharField(choices=[('goatza', 'goatza'), ('external', 'External'), ('contact', 'contact')], default='goatza', max_length=20),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='external_apply_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='venue_link',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='venue_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddConstraint(
            model_name='recruitment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('apply_method', 'external'), ('external_apply_url__isnull', False)), models.Q(('apply_method', 'external'), _negated=True), _connector='OR'), name='external_apply_url_required'),
        ),
        migrations.AddField(
            model_name='recruitmentagecategory',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_categories', to='recruitments.recruitment'),
        ),
        migrations.AddField(
            model_name='recruitmentcontact',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='recruitments.recruitment'),
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='max_age',
        ),
        migrations.RemoveField(
            model_name='recruitment',
            name='min_age',
        ),
        migrations.AddIndex(
            model_name='recruitmentagecategory',
            index=models.Index(fields=['recruitment'], name='recruitment_recruit_695844_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcontact',
            index=models.Index(fields=['recruitment'], name='recruitment_recruit_a4c1ee_idx'),
        ),
        migrations.AddIndex(
            model_name='recruitmentcontact',
            index=models.Index(fields=['contact_type'], name='recruitment_contact_3d342b_idx'),
        ),
    ]
