# Generated by Django 6.0.3 on 2026-05-16 10:23

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0003_recruitmentagecategory_recruitmentcontact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('icon_name', models.CharField(blank=True, max_length=50)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='recruitments.recruitment')),
            ],
            options={
                'db_table': 'recruitment_benefits',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['recruitment'], name='recruitment_recruit_e136f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='RecruitmentRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='recruitments.recruitment')),
            ],
            options={
                'db_table': 'recruitment_requirements',
                'ordering': ['display_order'],
                'indexes': [models.Index(fields=['recruitment'], name='recruitment_recruit_e2cf1a_idx')],
            },
        ),
    ]
