# Generated by Django 6.0.3 on 2026-07-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0004_recruitmentbenefit_recruitmentrequirement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruitmentmedia',
            name='file_url',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='recruitmentmedia',
            name='thumbnail_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
