# Generated by Django 6.0.3 on 2026-09-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitments', '0008_recruitmentdiscoverimpression'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='last_applicant_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
