# Generated by Django 6.0.3 on 2026-09-06 12:24

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_organizationlocation_location'),
        ('recruitments', '0009_recruitment_last_applicant_alert_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedRecruitment',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_recruitments', to='organization.organization')),
                ('recruitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='recruitments.recruitment')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_recruitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'saved_recruitments',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('org__isnull', True), ('user__isnull', False)), models.Q(('org__isnull', False), ('user__isnull', True)), _connector='OR'), name='saved_recruitment_user_or_org'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'recruitment'), name='unique_saved_recruitment_user'), models.UniqueConstraint(condition=models.Q(('org__isnull', False)), fields=('org', 'recruitment'), name='unique_saved_recruitment_org')],
            },
        ),
    ]
