# Generated by Django 6.0.3 on 2026-08-26 06:46

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0009_alter_organization_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('blocked_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to='organization.organization')),
                ('blocked_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_received', to=settings.AUTH_USER_MODEL)),
                ('blocker_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to='organization.organization')),
                ('blocker_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocks_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blocks',
                'indexes': [models.Index(fields=['blocker_user'], name='blocks_blocker_4eaca0_idx'), models.Index(fields=['blocker_org'], name='blocks_blocker_ee435c_idx'), models.Index(fields=['blocked_user'], name='blocks_blocked_9ab4af_idx'), models.Index(fields=['blocked_org'], name='blocks_blocked_ef77de_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('blocker_org__isnull', True), ('blocker_user__isnull', False)), models.Q(('blocker_org__isnull', False), ('blocker_user__isnull', True)), _connector='OR'), name='blocker_user_or_org'), models.CheckConstraint(condition=models.Q(models.Q(('blocked_org__isnull', True), ('blocked_user__isnull', False)), models.Q(('blocked_org__isnull', False), ('blocked_user__isnull', True)), _connector='OR'), name='blocked_user_or_org'), models.UniqueConstraint(condition=models.Q(('blocked_user__isnull', False), ('blocker_user__isnull', False)), fields=('blocker_user', 'blocked_user'), name='unique_user_blocks_user'), models.UniqueConstraint(condition=models.Q(('blocked_org__isnull', False), ('blocker_user__isnull', False)), fields=('blocker_user', 'blocked_org'), name='unique_user_blocks_org'), models.UniqueConstraint(condition=models.Q(('blocked_user__isnull', False), ('blocker_org__isnull', False)), fields=('blocker_org', 'blocked_user'), name='unique_org_blocks_user'), models.UniqueConstraint(condition=models.Q(('blocked_org__isnull', False), ('blocker_org__isnull', False)), fields=('blocker_org', 'blocked_org'), name='unique_org_blocks_org'), models.CheckConstraint(condition=models.Q(models.Q(('blocker_user', models.F('blocked_user')), _negated=True), models.Q(('blocker_org', models.F('blocked_org')), _negated=True)), name='block_not_self')],
            },
        ),
    ]
