# Generated by Django 6.0.3 on 2026-08-12 12:48

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0008_organizationprofile_is_public_profile'),
        ('posts', '0011_remove_savedpost_unique_saved_post_savedpost_org_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorAffinity',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affinity_as_author', to='organization.organization')),
                ('author_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affinity_as_author', to=settings.AUTH_USER_MODEL)),
                ('viewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actor_affinities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'actor_affinities',
                'indexes': [models.Index(fields=['viewer'], name='actor_affin_viewer__328237_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('author_org__isnull', True), ('author_user__isnull', False)), models.Q(('author_org__isnull', False), ('author_user__isnull', True)), _connector='OR'), name='affinity_author_user_or_org'), models.UniqueConstraint(condition=models.Q(('author_user__isnull', False)), fields=('viewer', 'author_user'), name='unique_affinity_viewer_author_user'), models.UniqueConstraint(condition=models.Q(('author_org__isnull', False)), fields=('viewer', 'author_org'), name='unique_affinity_viewer_author_org')],
            },
        ),
        migrations.CreateModel(
            name='PostImpression',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('last_seen_at', models.DateTimeField()),
                ('seen_count', models.PositiveIntegerField(default=1)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_impressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post_impressions',
                'indexes': [models.Index(fields=['user', 'last_seen_at'], name='post_impres_user_id_5dd4ec_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'post'), name='unique_user_post_impression')],
            },
        ),
    ]
