# Generated by Django 6.0.3 on 2026-07-29 17:08

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0009_postmedia_height_postmedia_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlight',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=80)),
                ('file_url', models.URLField()),
                ('public_id', models.CharField(max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('duration', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('everyone', 'Everyone'), ('followers_and_recruiters', 'Followers and recruiters'), ('recruiters_only', 'Recruiters only')], default='followers_and_recruiters', max_length=30)),
                ('order', models.PositiveIntegerField(default=0)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_highlights', to='posts.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'highlights',
                'indexes': [models.Index(fields=['user', 'is_deleted'], name='highlights_user_id_75b681_idx'), models.Index(fields=['user', 'order'], name='highlights_user_id_bf0a63_idx')],
            },
        ),
    ]
