# Generated by Django 6.0.3 on 2026-07-30 06:51

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('highlights', '0002_alter_highlight_file_url_and_more'),
        ('organization', '0007_organizationprofile_organizatio_followe_3e8bda_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightView',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('is_recruiter', models.BooleanField(default=False)),
                ('viewed_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('highlight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='highlights.highlight')),
                ('viewer_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_views', to='organization.organization')),
                ('viewer_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='highlight_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'highlight_views',
                'indexes': [models.Index(fields=['highlight', 'is_recruiter'], name='highlight_v_highlig_c1225a_idx'), models.Index(fields=['highlight', 'viewed_on'], name='highlight_v_highlig_5a3b44_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('viewer_org__isnull', True), ('viewer_user__isnull', False)), models.Q(('viewer_org__isnull', False), ('viewer_user__isnull', True)), _connector='OR'), name='highlight_view_user_or_org'), models.UniqueConstraint(condition=models.Q(('viewer_user__isnull', False)), fields=('highlight', 'viewer_user', 'viewed_on'), name='unique_user_highlight_view_per_day'), models.UniqueConstraint(condition=models.Q(('viewer_org__isnull', False)), fields=('highlight', 'viewer_org', 'viewed_on'), name='unique_org_highlight_view_per_day')],
            },
        ),
    ]
