# Generated by Django 6.0.3 on 2026-04-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_like_unique_user_post_like_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmedia',
            name='public_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
