# Generated by Django 6.0.3 on 2026-04-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_postmedia_public_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(choices=[('like', 'Like'), ('fire', 'Fire'), ('respect', 'Respect'), ('funny', 'Funny')], default='like', max_length=10),
        ),
    ]
