# Generated by Django 6.0.3 on 2026-08-06 06:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organizationprofile_organizatio_followe_3e8bda_idx'),
        ('posts', '0009_postmedia_height_postmedia_width'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='postmention',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='postmention',
            constraint=models.UniqueConstraint(condition=models.Q(('mentioned_user__isnull', False)), fields=('post', 'mentioned_user'), name='unique_post_mention_user'),
        ),
        migrations.AddConstraint(
            model_name='postmention',
            constraint=models.UniqueConstraint(condition=models.Q(('mentioned_org__isnull', False)), fields=('post', 'mentioned_org'), name='unique_post_mention_org'),
        ),
    ]
