# Generated by Django 6.0.3 on 2026-08-06 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_organizationprofile_organizatio_followe_3e8bda_idx'),
        ('posts', '0010_postmention_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='savedpost',
            name='unique_saved_post',
        ),
        migrations.AddField(
            model_name='savedpost',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='savedpost',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='savedpost',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('org__isnull', True), ('user__isnull', False)), models.Q(('org__isnull', False), ('user__isnull', True)), _connector='OR'), name='saved_post_user_or_org'),
        ),
        migrations.AddConstraint(
            model_name='savedpost',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'post'), name='unique_saved_post_user'),
        ),
        migrations.AddConstraint(
            model_name='savedpost',
            constraint=models.UniqueConstraint(condition=models.Q(('org__isnull', False)), fields=('org', 'post'), name='unique_saved_post_org'),
        ),
    ]
