# Generated by Django 6.0.3 on 2026-04-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_userfcmtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfcmtoken',
            name='device_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
