# Generated by Django 6.0.3 on 2026-07-17 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_back', 'Follow Back'), ('like', 'Like'), ('comment', 'Comment'), ('recruitment_application', 'Recruitment Application'), ('recruitment_application_status', 'Recruitment Application Status'), ('message', 'Message')], max_length=30),
        ),
    ]
