# Generated by Django 6.0.3 on 2026-08-03 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
        ('notifications', '0008_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='achievements.achievement'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_back', 'Follow Back'), ('like', 'Like'), ('comment', 'Comment'), ('recruitment_application', 'Recruitment Application'), ('recruitment_application_status', 'Recruitment Application Status'), ('message', 'Message'), ('career_verification_request', 'Career Verification Request'), ('career_verified', 'Career Verified'), ('career_rejected', 'Career Rejected'), ('career_add_prompt', 'Career Add Prompt'), ('achievement_verification_request', 'Achievement Verification Request'), ('achievement_verified', 'Achievement Verified'), ('achievement_rejected', 'Achievement Rejected')], max_length=40),
        ),
    ]
