# Generated by Django 6.0.3 on 2026-08-26 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_alter_achievement_image'),
        ('careers', '0001_initial'),
        ('notifications', '0010_alter_notification_type'),
        ('organization', '0010_organization_is_suspended'),
        ('posts', '0012_postmedia_size_bytes'),
        ('recruitments', '0008_recruitmentdiscoverimpression'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notification',
            name='notification_actor_user_or_org',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_back', 'Follow Back'), ('like', 'Like'), ('comment', 'Comment'), ('mention', 'Mention'), ('recruitment_application', 'Recruitment Application'), ('recruitment_application_status', 'Recruitment Application Status'), ('message', 'Message'), ('career_verification_request', 'Career Verification Request'), ('career_verified', 'Career Verified'), ('career_rejected', 'Career Rejected'), ('career_add_prompt', 'Career Add Prompt'), ('achievement_verification_request', 'Achievement Verification Request'), ('achievement_verified', 'Achievement Verified'), ('achievement_rejected', 'Achievement Rejected'), ('moderation_warning', 'Moderation Warning')], max_length=40),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('actor_org__isnull', True), ('actor_user__isnull', False)), models.Q(('actor_org__isnull', False), ('actor_user__isnull', True)), models.Q(('actor_org__isnull', True), ('actor_user__isnull', True)), _connector='OR'), name='notification_actor_user_or_org'),
        ),
    ]
