# Generated by Django 6.0.3 on 2026-04-10 09:35

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('posts', '0008_post_city_post_country_code_post_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('follow', 'Follow'), ('follow_back', 'Follow Back'), ('like', 'Like'), ('comment', 'Comment')], max_length=20)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('group_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('dedup_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('is_batched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to='organization.organization')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='triggered_notifications', to=settings.AUTH_USER_MODEL)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
                ('recipient_org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='organization.organization')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['recipient_user', '-created_at'], name='notificatio_recipie_19f5f7_idx'), models.Index(fields=['recipient_org', '-created_at'], name='notificatio_recipie_368f2f_idx'), models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'), models.Index(fields=['type'], name='notificatio_type_8a8a78_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('recipient_org__isnull', True), ('recipient_user__isnull', False)), models.Q(('recipient_org__isnull', False), ('recipient_user__isnull', True)), _connector='OR'), name='notification_recipient_user_or_org'), models.CheckConstraint(condition=models.Q(models.Q(('actor_org__isnull', True), ('actor_user__isnull', False)), models.Q(('actor_org__isnull', False), ('actor_user__isnull', True)), _connector='OR'), name='notification_actor_user_or_org')],
            },
        ),
    ]
