# Generated by Django 6.0.3 on 2026-07-05 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_userfcmtoken_device_name'),
        ('recruitments', '0006_recruitmentapplication_shared_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recruitment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitments.recruitment'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_back', 'Follow Back'), ('like', 'Like'), ('comment', 'Comment'), ('recruitment_application', 'Recruitment Application')], max_length=30),
        ),
    ]
