# Generated by Django 6.0.3 on 2026-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_notification_career_entry_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_back', 'Follow Back'), ('like', 'Like'), ('comment', 'Comment'), ('recruitment_application', 'Recruitment Application'), ('recruitment_application_status', 'Recruitment Application Status'), ('message', 'Message'), ('career_verification_request', 'Career Verification Request'), ('career_verified', 'Career Verified'), ('career_rejected', 'Career Rejected'), ('career_add_prompt', 'Career Add Prompt')], max_length=30),
        ),
    ]
