# Generated by Django 6.0.3 on 2026-09-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_back', 'Follow Back'), ('like', 'Like'), ('comment', 'Comment'), ('mention', 'Mention'), ('recruitment_application', 'Recruitment Application'), ('recruitment_application_status', 'Recruitment Application Status'), ('recruitment_announcement', 'Recruitment Announcement'), ('trial_reminder', 'Trial Reminder'), ('message', 'Message'), ('career_verification_request', 'Career Verification Request'), ('career_verified', 'Career Verified'), ('career_rejected', 'Career Rejected'), ('career_add_prompt', 'Career Add Prompt'), ('achievement_verification_request', 'Achievement Verification Request'), ('achievement_verified', 'Achievement Verified'), ('achievement_rejected', 'Achievement Rejected'), ('moderation_warning', 'Moderation Warning')], max_length=40),
        ),
    ]
