# Generated by Django 6.0.3 on 2026-08-15 11:09

import django.db.models.deletion
import uuid6
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('careers', '0001_initial'),
        ('sports', '0004_alter_sport_icon_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchDiarySettings',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('showcase_summary', models.BooleanField(default=False)),
                ('current_streak_weeks', models.PositiveIntegerField(default=0)),
                ('longest_streak_weeks', models.PositiveIntegerField(default=0)),
                ('last_logged_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='match_diary_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_diary_settings',
            },
        ),
        migrations.CreateModel(
            name='MatchEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('played', 'Played')], default='played', max_length=20)),
                ('date', models.DateField()),
                ('kickoff_time', models.TimeField(blank=True, null=True)),
                ('opponent_name', models.CharField(blank=True, max_length=150)),
                ('match_type', models.CharField(choices=[('league', 'League'), ('tournament', 'Tournament'), ('friendly', 'Friendly'), ('school_college', 'School / College'), ('practice', 'Practice'), ('other', 'Other')], default='other', max_length=20)),
                ('result', models.CharField(choices=[('win', 'Win'), ('loss', 'Loss'), ('draw', 'Draw'), ('na', 'Not applicable')], default='na', max_length=20)),
                ('minutes_played', models.PositiveIntegerField(blank=True, null=True)),
                ('self_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('photo_public_id', models.CharField(blank=True, max_length=255)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('followers', 'Followers'), ('public', 'Public')], default='private', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('career_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_entries', to='careers.careerentry')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_entries', to='sports.sportposition')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='match_entries', to='sports.sport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'match_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SportMatchStatField',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('short_label', models.CharField(blank=True, max_length=10)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('value_type', models.CharField(choices=[('integer', 'Integer'), ('decimal', 'Decimal')], max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('positions', models.ManyToManyField(blank=True, related_name='match_stat_fields', to='sports.sportposition')),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stat_fields', to='sports.sport')),
            ],
            options={
                'db_table': 'sport_match_stat_fields',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MatchEntryStat',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('match_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='matches.matchentry')),
                ('stat_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='matches.sportmatchstatfield')),
            ],
            options={
                'db_table': 'match_entry_stats',
            },
        ),
        migrations.AddIndex(
            model_name='matchentry',
            index=models.Index(fields=['user', 'is_deleted', 'date'], name='match_entri_user_id_2fed43_idx'),
        ),
        migrations.AddIndex(
            model_name='matchentry',
            index=models.Index(fields=['user', 'status', 'date'], name='match_entri_user_id_2e5573_idx'),
        ),
        migrations.AddIndex(
            model_name='matchentry',
            index=models.Index(fields=['user', 'sport', 'date'], name='match_entri_user_id_7d0391_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchentry',
            constraint=models.CheckConstraint(condition=models.Q(('self_rating__isnull', True), models.Q(('self_rating__gte', 1), ('self_rating__lte', 5)), _connector='OR'), name='match_entry_valid_self_rating'),
        ),
        migrations.AddConstraint(
            model_name='matchentry',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'played'), models.Q(('minutes_played__isnull', True), ('result', 'na'), ('self_rating__isnull', True)), _connector='OR'), name='match_entry_scheduled_has_no_result'),
        ),
        migrations.AddIndex(
            model_name='sportmatchstatfield',
            index=models.Index(fields=['sport', 'is_active', 'order'], name='sport_match_sport_i_63dabc_idx'),
        ),
        migrations.AddConstraint(
            model_name='sportmatchstatfield',
            constraint=models.UniqueConstraint(fields=('sport', 'name'), name='unique_sport_match_stat_field'),
        ),
        migrations.AddIndex(
            model_name='matchentrystat',
            index=models.Index(fields=['match_entry'], name='match_entry_match_e_fac795_idx'),
        ),
        migrations.AddConstraint(
            model_name='matchentrystat',
            constraint=models.UniqueConstraint(fields=('match_entry', 'stat_field'), name='unique_stat_per_match_entry'),
        ),
    ]
